name: dart_native_compression_bench
description: dart_native_compression_bench
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  benchmark_harness: any
  dart_native_compression:
    path: ../

dev_dependencies:
  test: any
