name: dart_native_compression
description: A dart binding to native compression libraries
version: 1.0.0
homepage: https://github.com/hanabi1224/flutter_native_extensions/tree/master/src/compression/dart_native_compression
publish_to: https://pub.dev/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  collection: ^1.40.0

dev_dependencies:
  test: any
