name: dart_native_compression
description: A dart binding to native compression libraries, including lz4@1.9.3.
version: 1.1.0+2
homepage: https://github.com/hanabi1224/flutter_native_extensions/tree/master/src/compression/dart_native_compression
publish_to: https://pub.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.0.0
  collection: ^1.15.0

dev_dependencies:
  test: any
  pedantic: any
