dart_native_compression_task:
  container:
    dockerfile: .ci/FlutterRust/Dockerfile
  pub_cache:
    folder: ~/.pub-cache
  git_submodule_script:
    - git submodule update --recursive
  test_script:
    - cd src/compression/dart_native_compression
    - pub get
    - pub run test
