dart_native_compression_task:
  container:
    dockerfile: .ci/FlutterRust/Dockerfile
  pub_cache:
    folder: ~/.pub-cache
  cargo_cache:
    folder: $HOME/.cargo/registry
  setup_script:
    - git submodule update --init --recursive
  cargo_test_script:
    - source $HOME/.cargo/env
    - cd src/compression/native_compression
    - cargo build --release --verbose
    - cargo test --release -- --nocapture
  dart_test_script:
    - source $HOME/.cargo/env
    - cd src/compression/dart_native_compression
    - pub get
    - pub run test
  dart_bench_script:
    - source $HOME/.cargo/env
    - cd src/compression/dart_native_compression/bench
    - pub get
    - dart main.dart
