name: dart_native_annoy
description: A dart binding to native annoy library to serve pre-built Annoy index.
version: 0.2.0+1
homepage: https://github.com/hanabi1224/flutter_native_extensions/tree/master/src/annoy/dart_native_annoy
# publish_to: https://pub.dev/

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  test: any
  lints: any
